<?php

//get the subscriber id from the firestore database aswell as the email or userid
//and store it in $subscriberId variable
$token = $_GET['access_token'];

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://api-m.sandbox.paypal.com/v1/billing/subscriptions/'.rawurlencode($subscriberID).'/cancel');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n  \"reason\": \"Not satisfied with the service\"\n}");

$headers = array();
$headers[] = 'Content-Type: application/json';
$headers[] = 'Authorization: Bearer '.rawurlencode($token);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
$err = curl_error($ch);
curl_close($ch);
if($err)
{
    echo'error'.$err;
}
else
{
    //update firestore database and set the status to 'CANCELLED' and empty everything;
    /*if(update sucess)
    {
        header("location: cancelsuccess.php?subscription=cancelled");
        exit();
    }else
    {
        echo'error';
    }*/
}
?>