<?php
$token = $_GET['access_token'];
$unique_id = md5(uniqid());
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://api-m.sandbox.paypal.com/v1/catalogs/products');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n  \"name\": \"Video Streaming\",\n  \"description\": \"A video streaming service\",\n  \"type\": \"SERVICE\",\n  \"category\": \"SOFTWARE\",\n  \"image_url\": \"https://example.com/streaming.jpg\",\n  \"home_url\": \"https://example.com/home\"\n}");

$headers = array();
$headers[] = 'Content-Type: application/json';
$headers[] = 'Authorization: Bearer '.rawurlencode($token);
$headers[] = 'Paypal-Request-Id:'.rawurlencode($unique_id);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
$err = curl_error($ch);
curl_close($ch);
if($err)
{
  echo'error:'.$err;
}else{
    $response = json_decode($result);
    //var_dump($response);
    $productID = $response->id;
    //var_dump($productID);
    if($productID)
    {
       header("Location: createPlan.php?productID=".$productID."&access_token=".$token);
        exit;
    }
}
?>