<?php
$subscriptionID = $_GET['subscriptionID'];
$token = $_GET['access_token'];

if($subscriptionID == "" || $token == "")
{
    //header("Location: javascript://history.go(-1)");
    echo 'error';
}

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://api-m.sandbox.paypal.com/v1/billing/subscriptions/'.rawurlencode($subscriptionID));
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


$headers = array();
$headers[] = 'Content-Type: application/json';
$headers[] = 'Authorization: Bearer '.rawurlencode($token);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
$err = curl_error($ch);
curl_close($ch);
if($err)
{
    echo'error'.$err;
}
else{
    $response = json_decode($result);
    //$email = $owneremail;  //user id or email;
    $status = $response->status;
    $subscriberID = $response->$id;
    $PlanID = $response->plan_id;
    $start_time = $response->start_time;
    $status_update_time = $response->status_update_time;
    $payment_email_address = $response->subscriber->email_address;
    $given_name = $response->subscriber->name->given_name;
    $surname = $response->subscriber->name->surname;
    $fullname = $given_name."".$surname;
    $payerID = $response->subscriber->payer_id;

    if($status == 'ACTIVE' && $subscriptionID == $subscriberID)
    {
        //put the data in the database firestore
        /*if(sucess)
        {
            header("Location: success page");
            exit();
        }else
        {
            echo'error';
        }*/
    }






}
?>